version: '2'

services:
  # Jenkins Master
  jenkins:
    image: blacklabelops/jenkins:alpine
    container_name: jenkins
    hostname: jenkins
    networks:
      - jenkinsnet
    ports:
     - "8090:8080"
    volumes:
      - jenkinsdata:/jenkins
      - jenkinslogs:/var/log
    env_file:
      - jenkins-master.env
    labels:
      com.blacklabelops.description: "Jenkins Continuous Integration System"
      com.blacklabelops.service: "jenkins-master"
  # Jenkins Slave
  slave:
    image: blacklabelops/swarm-jdk8
    networks:
      - jenkinsnet
    env_file:
      - jenkins-slave.env
    labels:
      com.blacklabelops.description: "Jenkins Swarm JDK-8 Slave"
      com.blacklabelops.service: "slave"
      com.blacklabelops.applications: "java maven gradle"

volumes:
  jenkinsdata:
    external: false
  jenkinslogs:
    external: false

networks:
  jenkinsnet:
    driver: bridge
